# Imports

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

/home/gaspa/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "


In [4]:
def drawview(matrice):
    #matrice is like [column of x values, column of y values]
    x = matrice[:,0]
    y = matrice[:,1]
    plt.scatter(x, y)
    plt.show()

In [ ]:
# drawview(np.array(np.random.rand(500,2)))

In [5]:
df = pd.read_csv('test.csv', delimiter=',')
df = df.rename(columns=lambda x: x.strip())
ef = pd.read_csv('sample_submission.csv', delimiter=',')
ef = ef.rename(columns=lambda x: x.strip())

In [62]:
def fix_nonintdata (df):
    # this transform the data that are not numbers into numbers
    # first we create a cursor that scan every column
    for column in df.columns:
        # then we check if the column is not a number
        if df[column].dtype == 'object':
            # if it is not a number, we add every possible value to a dictionnary
            convert_dict = {}
            for i, value in enumerate(df[column].unique()):
                convert_dict[value] = i
            # then we replace the value by the corresponding number
            df[column] = df[column].map(convert_dict)
    return df

In [63]:
print(fix_nonintdata(df))

        Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  \
0     1461          20         0         80.0    11622       0      0   
1     1462          20         1         81.0    14267       0      0   
2     1463          60         1         74.0    13830       0      0   
3     1464          60         1         78.0     9978       0      0   
4     1465         120         1         43.0     5005       0      0   
...    ...         ...       ...          ...      ...     ...    ...   
1454  2915         160         2         21.0     1936       0      0   
1455  2916         160         2         21.0     1894       0      0   
1456  2917          20         1        160.0    20000       0      0   
1457  2918          85         1         62.0    10441       0      0   
1458  2919          60         1         74.0     9627       0      0   

      LotShape  LandContour  Utilities  ...  ScreenPorch  PoolArea  PoolQC  \
0            0            0          0  ...  

In [64]:
ncols = df.shape[1]
param = df.columns[1:]
price = ef.columns[1:]
X = fix_nonintdata(df[param]).to_numpy()
Y = ef[price].to_numpy()

In [65]:
# get n and p values here
n, p = X.shape

In [66]:
# add column with constant one to X here
one = np.ones( (n, 1), dtype=X.dtype)
X = np.hstack( [one, X] )

In [73]:
print(X.df)

[[1.000e+00 2.000e+01 0.000e+00 ... 2.010e+03 0.000e+00 0.000e+00]
 [1.000e+00 2.000e+01 1.000e+00 ... 2.010e+03 0.000e+00 0.000e+00]
 [1.000e+00 6.000e+01 1.000e+00 ... 2.010e+03 0.000e+00 0.000e+00]
 ...
 [1.000e+00 2.000e+01 1.000e+00 ... 2.006e+03 0.000e+00 2.000e+00]
 [1.000e+00 8.500e+01 1.000e+00 ... 2.006e+03 0.000e+00 0.000e+00]
 [1.000e+00 6.000e+01 1.000e+00 ... 2.006e+03 0.000e+00 0.000e+00]]


In [71]:
# compute beta in a numpy array here
beta = np.linalg.inv(X.T @ X) @ X.T @ Y

In [77]:
colnames = df.columns[1:] 
coefnames = pd.Index(["CONST"]).append(df.columns[1:])

In [79]:
pd.DataFrame(beta.reshape(1,p+1), columns = colnames, index=['Means'] )

ValueError: Shape of passed values is (1, 80), indices imply (1, 79)

In [69]:
SST = np.sum( (Y - np.mean(Y))**2 )
SSR = np.sum( (X @ beta - np.mean(Y))**2 )
SSE = np.sum( (Y - X @ beta)**2 )

print(SST, SSR, SSE)

397821621423.4338 nan nan
